[tool.black]
line-length = 100
target-version = ["py38"]
exclude = ["wheel/", "archive/"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "E266", "E501", "W503"]
exclude = [".git", "__pycache__", "build", "dist", "wheel", "archive"]